### ISSUE TITLE
Add guidance on when to flag posts for Noah

### ISSUE THREAD

**Issue by awfrancisco** [18F/blogging-guide#6]
@NoahKunin Can you add a couple of bullets to this page about when authors and editors should include you on the review of posts? https://github.com/18F/blogging-guide/edit/18f-pages/pages/publishing-process.md

Thanks

**Comment by quepol** [comment]
@awfrancisco if everything looks good in that update, feel free to close this issue.

**Comment by awfrancisco** [comment]
Looks good.
